name: Init project 

on: 
    workflow_call:
      inputs:
        projectName:
          required: true
          type: string
    workflow_dispatch:
      inputs:
        projectName:
          required: true
          type: string

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create project repo 
        run: echo Creating ${{ inputs.projectName }} repo.

  init-wiki:
    uses: bromba-noesis/workflows/.github/workflows/wiki.yml@main
    with:
      projectName: ${{ inputs.projectName }}
