name: Test

on:
  push:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  replace-placeholders:
    runs-on: ubuntu-latest
    env:
      PLACEHOLDERS_JSON: ${{ vars.PLACEHOLDERS_JSON }}  # Repository variable with JSON map

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show original file
        run: cat config.json

      - name: Replace placeholders dynamically
        run: |
          echo "Parsing placeholder map..."

          # Save JSON to a temporary file
          echo "$PLACEHOLDERS_JSON" > placeholders.json

          # Extract all placeholders from the file
          grep -o '{{[^}]\+}}' config.json | sort -u | while read -r placeholder; do
            var_name=$(echo "$placeholder" | sed 's/[{}]//g')

            # Get the value from the JSON map
            value=$(jq -r --arg key "$var_name" '.[$key]' placeholders.json)

            if [ "$value" != "null" ]; then
              echo "Replacing $placeholder with $value"
              sed -i "s/{{$var_name}}/$value/g" config.json
            else
              echo "Warning: No value found for $placeholder"
            fi
          done

          echo "Updated config.json:"
          cat config.json
