name: Init project wiki

on: 
    workflow_call:
      inputs:
        projectName:
          required: true
          type: string
    workflow_dispatch:
      inputs:
        projectName:
          required: true
          type: string

jobs:
  init-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Init project wiki 
        run: echo Creating ${{ inputs.projectName }} wiki pages.

  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Update project index page
        run: echo Adding ${{ inputs.projectName }} to the index page.
